<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<div id="mainContent">
    <div id="header">
        <h1>Basket <i class="fa fa-shopping-cart"></i></h1>
        <h3>Shopping Basket</h3>
    </div>
    <div id="basket">
        <table>
            <tr>
                <th>Product</th>
<!--                <th>Color</th>-->
<!--                <th>Size</th>-->
                <th>Price</th>
                <th>Quantity</th>
                <th>Cost</th>
                <th></th>
            </tr>
            <tr>
                <?php foreach ($cart as $elem): ?>
                <td>Product  <?php echo $elem['product_id']?></td>
<!--                <td><select class="color" name="mySelect" onChange="this.style.backgroundColor=this.options[this.selectedIndex].style.backgroundColor">-->
<!--                        <option value="1" style="background-color:#FFFFFF"></option>-->
<!--                        <option value="2" style="background-color:#000000"></option>-->
<!--                        <option value="3" style="background-color:#FF0000"></option>-->
<!--                        <option value="4" style="background-color:#008000"></option>-->
<!--                        <option value="5" style="background-color:#0000FF"></option>-->
<!--                    </select>-->
<!--                </td>-->
<!--                <td>-->
<!--                    <select class="size">-->
<!--                        <option value="S">S</option>-->
<!--                        <option value="M">M</option>-->
<!--                        <option value="L">L</option>-->
<!--                        <option value="XL">XL</option>-->
<!--                        <option value="XXL">XXL</option>-->
<!--                    </select>-->
<!--                </td>-->
                <td>&#36;<input name="price" class="price" value="<?php echo $productsWithKeyId[$elem['product_id']]['price'] ?>" /></td>
                <td>
                    <i class="fa fa-minus" title="Decrease Qty"></i>
                    <input class="qty" value="<?php echo $elem['amount']?>" name="qty" maxlength="2" />
                    <i class="fa fa-plus" title="Increase Qty"></i>
                </td>
                <td>&#36;<input name="cost" class="cost" value="<?php echo $productsWithKeyId[$elem['product_id']]['price'] * $elem['amount'] ?>" /></td>
                <form action="/deleteProduct" method="POST">
                    <td class="button"><button type="submit" class="fa fa-trash-o" title="Delete Item" ></button></td>
                    <input name="id" class="price" value="<?php echo $elem['product_id'] ?>" />
                </form>
            </tr>
            <?php endforeach; ?>
        </table>
        <div id="totalAmount">
            <div class="left">
                <h1>Total Cost</h1>
                <p>*Including all taxes</p>
            </div>
            <div class="right">
                &#36;<input name="total" id="total" value="53.96" />
            </div>
        </div>
        <form action="/delete" method="POST">
        <div id="button">
            <h1>DEL</h1><button type="submit" class="fa fa-shopping-cart"></button>
        </div>
        </form>
    </div>
    <div class="hide">
        <p>An interactive shopping basket </p>
    </div>
</div>


<style>

    body {
        background: url("https://celes.club/uploads/posts/2022-05/1653968424_1-celes-club-p-akatsuki-oboi-na-telefon-krasivie-1.png") no-repeat center center fixed;
        display: flex;
        flex-direction: row;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
    }

    /*reset browser*/
    html, body, div, span, h1, h2, h3, h4, h5, h6, p, img, i, dt, dd, ol, ul, li, form, table, tbody, tfoot, thead, tr, th, td,
    article, aside, canvas, details, footer, header, hgroup, menu, nav {
        margin: 0;
        padding: 0;
        border: 0;
        font-size: 100%;
        font: inherit;
        vertical-align: baseline;
    }
    article, aside, details, figcaption, figure,
    footer, header, hgroup, menu, nav, section {
        display: block;
    }
    body {
        line-height: 1;
    }
    table {
        border-collapse: collapse;
        border-spacing: 0;
    }
    a {
        text-decoration: none;
    }
    /*end*/

    body {
        font: 100% Georgia, serif;
        color: #25343F;
        margin-top:25px;
    }

    h1 {
        font-size: 32px;
        font-weight:bold;
    }

    input {
        font-size: 15px;
        color: #25343F;
        border: 0px;
        margin: 0px;
        width: 40px;
        background-color: rgb(211,211,211);
    }

    select {
        width: 50px;
        /*background-color: rgb(211,211,211);*/
        border: 0px;
    }

    select.size {
        background-color: rgb(211,211,211);
    }

    #mainContent {
        width: 800px;
        margin: auto;
        padding: 10px 20px 30px;
        background-color: rgba(211,211,211,0.8);
    }

    #header {
        width: 100%;
        height: 140px;
        text-align: right;
    }

    #header h1 {
        margin-bottom: 10px;
    }

    #header  i {
        color: rgb(181,0,0);
        font-size: 55px;
        text-shadow: 2px 2px 8px;
    }

    #basket {
        margin: auto;
    }

    #basket table {
        font-size: 18px;
        width: 100%;
        text-align: left;
    }

    #basket table td, th {
        border-right: 2px solid #25343F;
        padding: 5px;
        text-align: center;
    }

    #basket table th {
        font-size: 24px;
        padding-bottom: 10px;
        border: 0px;
    }

    #basket table td.button{
        border:none;
    }

    #basket i {
        cursor: pointer;
    }

    #totalAmount {
        height: 80px;
        margin-top: 25px;
        text-align: right;
    }

    #button {
        text-align: right;
        font-size: 65px;
        height: 110px;
        margin-right: 25px;
    }

    #button a {
        color: #25343F;
    }

    input.cost {
        width: 70px;
    }

    .qty {
        text-align: center;
        width: 25px;
    }

    .left {
        float:left;
        width: 450px;
    }

    .left p {
        font-size: 14px;
    }

    .right {
        font-size: 36px;
        margin-right: 20px;
    }

    .right input {
        font-size: 36px;
        width: 130px;
    }

    .hide {
        text-align: center;
        display: none;
    }

    #button a:hover i {
        -webkit-transform: rotate(360deg);
        -moz-transform: rotate(360deg);
        -ms-transform: rotate(360deg);
        -o-transform: rotate(360deg);
        transform: rotate(360deg);
        -webkit-transition: all 1s;
        -moz-transition: all 1s;
        -ms-transition: all 1s;
        -o-transition: all 1s;
        transition: all 2s;
        color: rgb(181,0,0);
        text-shadow: 3px 3px 8px;
    }

</style>