<head>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@700&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/6ab9ac06da.js" crossorigin="anonymous"></script>
</head>

<body>

<?php foreach ($products as $product): ?>
<div class="container ">
    <div class="card asics">
        <p class="price"><?php echo $product['price'] . 'Rub'?></p>

        <i class="info fas fa-info-circle"></i>

        <div class="imgBx">
            <img src="<?php echo $product['image url']?>">
        </div>
        <div class="contentBx  ">
            <h2><?php echo $product['product_name']?></h2>

            <div class="size">
                <h3><?php echo $product['description']?></h3>
            </div>

            <form action="/add-to-cart" method="POST">
                <button> Add to Cart</button>
                <input type="hidden" name="product_id" value="<?php echo $product['id']; ?>">

            <br><br>

                <div class="quantity-field" >
                    <button
                            class="value-button decrease-button"
                            onclick="decreaseValue(this)"
                            title="Azalt">-</button>
                    <div class="number">0</div>
                    <button
                            class="value-button increase-button"
                            onclick="increaseValue(this, 5)"
                            title="Arrtır"
                    >+
                    </button>
                </div>
            </form>

        </div>
    </div>


</div>
<?php endforeach; ?>
<div class="buttons">
    <a href="cart" style="color:blue" class="register-link">Go to Cart</a>
    <br>
    <a href="profile" style="color:red" class="register-link">My Profile</a>
</div>

</body>

<script>
    function increaseValue(button, limit) {
        const numberInput = button.parentElement.querySelector('.number');
        var value = parseInt(numberInput.innerHTML, 10);
        if(isNaN(value)) value = 0;
        if(limit && value >= limit) return;
        numberInput.innerHTML = value+1;
    }


    function decreaseValue(button) {
        const numberInput = button.parentElement.querySelector('.number');
        var value = parseInt(numberInput.innerHTML, 10);
        if(isNaN(value)) value = 0;
        if(value < 1) return;
        numberInput.innerHTML = value-1;
    }

</script>

<style>
    * {
        margin: 0;
        padding: 0;
        font-family: Quicksand;
    }
    body {
        background: url("https://foni.club/uploads/posts/2023-02/1677063387_foni-club-p-oboi-naruto-dlya-rabochego-stola-noutbuka-1.jpg") no-repeat center center fixed;
        display: flex;
        flex-direction: row;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
    }

    .price {
        position: absolute;
        top: 1em;
        right: 1em;
        backdrop-filter: blur(8px);
        background-color: rgba(0, 0, 0, 0.112);
        box-shadow: rgba(0, 0, 0, 0.3) 2px 8px 8px;
        border: 0px rgba(255, 255, 255, 0.4) solid;
        border-bottom: 0px rgba(40, 40, 40, 0.35) solid;
        border-right: 0px rgba(40, 40, 40, 0.35) solid;
        padding: 5px 10px;
        font-size: 0.8em;
        border-radius: 4px;
    }

    .container {
        position: relative;
        padding: 0 20px;
    }
    .container .card {
        position: relative;
        width: 320px;
        height: 450px;
        border-radius: 20px;
        background: url("https://99px.ru/sstorage/53/2013/10/tmb_85843_4797.jpg");
        box-shadow: -20px -20px 25px #0e0e0e, 20px 20px 25px #dddddd;
        overflow: hidden;
    }

    .container .card:after {
        content: "";
        position: absolute;
        top: 30%;
        left: -20%;
        font-size: 12em;
        font-weight: 800;
        font-style: italic;
        color: rgba(255, 255, 255, 0.04);
    }
    .container .card .imgBx {
        position: absolute;
        top: 50%;
        transform: translateY(-50%);
        z-index: 200;
        width: 100%;
        height: 220px;
        transition: 0.5s ease-in-out;
    }
    .container .card:hover .imgBx {
        top: 0%;
        transform: translateY(0%);
    }
    .container .card .imgBx img {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%) rotate(-25deg);
        width: 270px;
    }
    .container .card .contentBx {
        position: absolute;
        bottom: 0;
        width: 100%;
        height: 50px;
        text-align: center;
        transition: 1s;
        z-index: 10;
    }
    .container .card:hover .contentBx {
        height: 210px;
    }
    .container .card .contentBx h2 {
        position: relative;
        font-weight: 600;
        letter-spacing: 1px;
        color: #F89716;
    }
    /* Shoe Size */
    .container .card .contentBx .size,
    .container .card .contentBx .color {
        display: flex;
        justify-content: center;
        align-items: center;
        padding: 8px 20px;
        transition: 0.5s;
        opacity: 0;
        visibility: hidden;
    }
    .container .card:hover .contentBx .size {
        opacity: 1;
        visibility: visible;
        translate-delay: 0.5s;
    }
    .container .card:hover .contentBx .color {
        opacity: 1;
        visibility: visible;
        translate-delay: 0.6s;
    }
    .container .card .contentBx .size h3,
    .container .card .contentBx .color h3 {
        color: #fff;
        font-weight: 300;
        font-size: 14px;
        text-transform: uppercase;
        letter-spacing: 2px;
        margin-right: 10px;
    }
    .container .card .contentBx .size span {
        width: 26px;
        height: 26px;
        text-align: center;
        line-height: 26px;
        font-size: 14px;
        display: inline-block;
        color: #111;
        background: #fff;
        margin: 0 5px;
        transition: 0.5s;
        border-radius: 4px;
        cursor: pointer;
    }

    /* Shoe color */
    .container .card .contentBx .color span {
        width: 20px;
        height: 20px;
        background: #ff0;
        border-radius: 50%;
        margin: 0 5px;
        cursor: pointer;
    }

    /* Button/ */
    .container .card .contentBx button {
        display: inline-block;
        padding: 10px 20px;
        background: #fff;
        border-radius: 4px;
        margin-top: 10px;
        text-decoration: none;
        font-weight: 600;
        color: #111;
        opacity: 0;
        transform: translateY(50px);
        transition: 0.5s;
        border: none;
    }
    .container .card:hover .contentBx button {
        opacity: 1;
        transform: translateY(0px);
        transform-delay: 0.75s;
        cursor: pointer;
    }

    .info {
        position: absolute;
        top: 1em;
        left: 1em;
        color: #fff;
        cursor: pointer;
        z-index: 300;
    }

    .text {
        display: none;
        color: #fff;
        padding: 2em;
        z-index: 299;
        position: relative;
        backdrop-filter: blur(20px);
        background-color: rgba(0, 0, 0, 0.2);
        height: 100%;
        text-shadow: 1px 0 0 #000, 0 -1px 0 #000, 0 1px 0 #000, -1px 0 0 #000;
    }
    .info:hover + .text {
        display: block;
    }
    .quantity-field {
        display: flex;
        justify-content: center;
        align-items: center;
        width: 120px;
        height: 40px;
        margin: 0 auto;
    }

    .quantity-field .value-button{
        border: 1px solid #ddd;
        margin: 0px;
        width: 40px;
        height: 100%;
        padding: 0;
        background: #eee;
        outline: none;
        cursor: pointer;
    }

    .quantity-field .value-button:hover {
        background: rgb(230, 230, 230);
    }

    .quantity-field .value-button:active{
        background: rgb(210, 210, 210);
    }

    .quantity-field .decrease-button {
        margin-right: -4px;
        border-radius: 8px 0 0 8px;
    }

    .quantity-field .increase-button {
        margin-left: -4px;
        border-radius: 0 8px 8px 0;
    }

    .quantity-field .number{
        display: inline-block;
        text-align: center;
        border: none;
        border-top: 1px solid #ddd;
        border-bottom: 1px solid #ddd;
        margin: 0px;
        width: 40px;
        height: 100%;
        line-height: 40px;
        font-size: 11pt;
        box-sizing: border-box;
        background: white;
        font-family: calibri;
    }

    .quantity-field .number::selection{
        background: none;
    }

    /*
    input[type=number]::-webkit-inner-spin-button,
    input[type=number]::-webkit-outer-spin-button {
        -webkit-appearance: none;
        margin: 0;
    }
    */


</style>